{
 "title": "Traffic & Errors",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic & Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orders per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(orders_created_total[1m]))\r\n",
       "legendFormat": "Orders/sec"
      }
     ]
    },
    {
     "title": "Failed orders per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(orders_failed_total[5m]))",
       "legendFormat": "Failed orders/sec"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 *\r\n(\r\n  sum(rate(orders_failed_total[15m]))\r\n  /\r\n  sum(rate(orders_created_total[15m]))\r\n)\r\n",
       "legendFormat": "Error rate %"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes (Cumulative)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total orders created",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(orders_created_total)\r\n", "legendFormat": "Total orders created" }
     ]
    },
    {
     "title": "Total failed orders",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(orders_failed_total)\r\n", "legendFormat": "Total failed orders" }
     ]
    }
   ]
  },
  {
   "title": "Order Value Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Order value P50 / P90 / P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(order_value_usd_bucket[5m])) by (le)\r\n)\r\n",
       "legendFormat": "P99 order value"
      },
      {
       "expr": "histogram_quantile(\r\n  0.9,\r\n  sum(rate(order_value_usd_bucket[5m])) by (le)\r\n)\r\n",
       "legendFormat": "P90 order value"
      },
      {
       "expr": "histogram_quantile(\r\n  0.5,\r\n  sum(rate(order_value_usd_bucket[5m])) by (le)\r\n)\r\n",
       "legendFormat": "P50 order value"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs (Loki)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "API logs (live)",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"api-service\"}"
      }
     ]
    },
    {
     "title": "API error logs over time (from logs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "direction": "backward",
       "expr": "count_over_time({service_name=\"api-service\"} |= \"failed\" [5m])"
      }
     ]
    },
    {
     "title": "Worker Logs (live)",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"worker-service\"}\r\n"
      }
     ]
    },
    {
     "title": "Worker total logs over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "direction": "backward",
       "expr": "count_over_time(\r\n  {service_name=\"worker-service\"}\r\n  [5m]\r\n)\r\n"
      }
     ]
    },
    {
     "title": "Worker error logs over time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 20 },
     "targets": [
      {
       "direction": "backward",
       "expr": "count_over_time(\r\n  {service_name=\"worker-service\"} |= \"failed\"\r\n  [5m]\r\n)\r\n"
      }
     ]
    }
   ]
  }
 ]
}